# install kind
# golang is installed in setup phase
- name: install docker
  pacman:
    name: docker
    state: present

# https://kind.sigs.k8s.io/docs/user/quick-start/
- name: install kind
  shell:
    cmd: go get sigs.k8s.io/kind@v0.9.0
  environment:
    GO111MODULE: "on"

- name: check kind is installed
  shell:
    cmd: kind --version

- name: create kind cluster
  shell:
    cmd: kind create cluster
  become: True
