- name: start kubernetes control plane
  shell:
    cmd: kubeadm init --control-plane-endpoint={{control_plane_ip}} --pod-network-cidr=10.244.0.0/16 --node-name=control-plane
  register: kubeadm_init_result
  failed_when:
  # get error
  - kubeadm_init_result.rc != 0
  become: True

# AFTER running kubeadm, this setting is required when you use cri-o
- name: set kubelet cgroup driver to systemd
  lineinfile:
    dest: /var/lib/kubelet/config.yaml
    regexp: "^cgroupDriver: \"systemd\""
    line: "cgroupDriver: \"systemd\""
  become: True

# TBD: daemon reload
- name: enable kubelet service
  systemd:
    daemon_reload: True
    state: restarted
    name: kubelet
  become: True
 
# TBD: remove master taint
#kubectl taint nodes control-plane node-role.kubernetes.io/master=:NoSchedule-
