- name: start kubernetes control plane
  shell:
    cmd: kubeadm init --control-plane-endpoint={{control_plane_ip}} --pod-network-cidr=10.244.0.0/16 --node-name={{kubeadm_control_plane_node_name}}
  register: kubeadm_init_result
  failed_when:
  # get error
  - kubeadm_init_result.rc != 0
  become: True

# AFTER running kubeadm, this setting is required when you use cri-o
- name: set kubelet cgroup driver to systemd
  lineinfile:
    dest: /var/lib/kubelet/config.yaml
    regexp: "^cgroupDriver: \"systemd\""
    line: "cgroupDriver: \"systemd\""
  become: True

- name: enable kubelet service
  systemd:
    daemon_reload: True
    state: restarted
    name: kubelet
  become: True
 
- name: add control-plane taint
  shell:
    cmd: kubectl taint nodes {{kubeadm_control_plane_node_name}} node-role.kubernetes.io/control-plane=:NoSchedule

# master taint will be removed after k8s 1.24
- name: remove taint
  shell:
    cmd: kubectl taint nodes {{kubeadm_control_plane_node_name}} node-role.kubernetes.io/master=:NoSchedule-
