# tasks for kubernetes worker
- name: join to kubernetes cluster
  shell:
    cmd: kubeadm join {{control_plane_ip}}:6443 --token {{kubeadm_token}} --discovery-token-ca-cert-hash {{kubeadm_ca_cert_hash}} --node-name {{kubeadm_worker_node_name}}
  become: True
