# tasks for kubernetes worker
- name: join to kubernetes cluster
  shell:
    cmd: kubeadm join {{control_plane_ip}}:6443 --token {{kubeadm_token}} --discovery-token-ca-cert-hash {{kubeadm_ca_cert_hash}} --node-name {{kubeadm_worker_node_name}} --cri-socket=unix:///var/run/crio/crio.sock
  register: kubeadm_join_result
  failed_when:
  # get error
  - kubeadm_join_result.rc != 0
  # kubeadm join fails when already kubelet is started via kubeadm
  - "'/etc/kubernetes/kubelet.conf already exists' not in kubeadm_join_result.stderr"
  - "'Port 10250 is in use' not in kubeadm_join_result.stderr"
  become: True

# AFTER running kubeadm, this setting is required when you use cri-o
# https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#configuring-the-kubelet-cgroup-driver
- name: set kubelet cgroup driver to systemd
  lineinfile:
    dest: /var/lib/kubelet/config.yaml
    regexp: "^cgroupDriver: \"systemd\""
    line: "cgroupDriver: \"systemd\""
  become: True

- name: enable kubelet service
  systemd:
    daemon_reload: True
    state: restarted
    name: kubelet
  become: True
 