# tasks for kubernetes worker
- name: join to kubernetes cluster
  shell:
    cmd: kubeadm join {{control_plane_ip}}:6443 --token {{kubeadm_token}} --discovery-token-ca-cert-hash {{kubeadm_ca_cert_hash}} --node-name {{kubeadm_worker_node_name}}
  register: kubeadm_join_result
  failed_when:
  # get error
  - kubeadm_join_result.rc != 0
  # kubeadm join fails when already kubelet is started via kubeadm
  - "'/etc/kubernetes/kubelet.conf already exists' not in kubeadm_join_result.stderr"
  - "'Port 10250 is in use' not in kubeadm_join_result.stderr"
  become: True
