# apply k8s manifests
- name: copy k8s manifests
  copy:
    src: ./
    dest: /home/ansible/k8s
    owner: ansible
    group: wheel
  become: True

- name: generate prometheus configmap
  template:
    src: prometheus-configmap.yaml.j2
    dest: /home/ansible/k8s/monitoring/prometheus-configmap.yaml

- name: apply k8s setup manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/setup

- name: apply workstation manifst
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/default/ws.yaml
 
- name: apply ingress manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/ingress

- name: apply monitoring manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/monitoring
  