# apply k8s manifests
- name: clean k8s manifests if exists
  file:
    path: /home/ansible/k8s
    state: absent

- name: copy k8s manifests
  copy:
    src: ./
    dest: /home/ansible/k8s
    owner: ansible
    group: wheel
  become: True

- name: apply k8s ingress manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/ingress
  # TODO: fix manifest so that it can apply idempotently
  register: apply_ingress_result
  failed_when:
  - '"field is immutable" not in apply_ingress_result.stderr'
  - 'apply_ingress_result.rc is not 0'

- name: generate prometheus configmap
  template:
    src: prometheus-configmap.yaml.j2
    dest: /home/ansible/k8s/base/monitoring/prometheus-configmap.yaml

- name: Append secretGenerator to base kustomization.yaml
  lineinfile:
    dest: /home/ansible/k8s/base/kustomization.yaml
    regexp: "^#REPLACED BY ANSIBLE"
    line: |
      secretGenerator:
      - name: mysql-pass
        namespace: sandbox
        literals:
        - password={{mysql_password}}

- name: apply base kustomization.yaml
  shell:
    cmd: /usr/bin/kubectl apply -k /home/ansible/k8s/base
