# apply k8s manifests
- name: copy k8s manifests
  copy:
    src: ./
    dest: /home/ansible/k8s
    owner: ansible
    group: wheel
  become: True

- name: generate prometheus configmap
  template:
    src: prometheus-configmap.yaml.j2
    dest: /home/ansible/k8s/monitoring/prometheus-configmap.yaml

- name: apply k8s setup manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/setup
  
- name: apply k8s ingress manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/ingress
  # TODO: fix manifest so that it can apply idempotently
  register: apply_ingress_result
  failed_when:
  - '"field is immutable" not in apply_ingress_result.stderr'
  - 'apply_ingress_result.rc is not 0'

- name: apply k8s monitoring manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/monitoring

- name: generate kustomization file for sandbox namespace
  template:
    src: sandbox-kustomization.yaml.j2
    dest: /home/ansible/k8s/sandbox/kustomization.yaml

- name: apply kustomization for sandbox namespace
  shell:
    cmd: /usr/bin/kubectl apply -k /home/ansible/k8s/sandbox/

- name: apply sandbox manifest
  shell:
    cmd: /usr/bin/kubectl apply -f /home/ansible/k8s/sandbox 