# setup cri-o
- name: enable overlay module
  command: modprobe overlay
  become: True

- name: enable br_netfilter module
  command: modprobe br_netfilter
  become: True

- name: install cri-o
  pacman:
    name: cri-o 
    state: present

- name: check netfilter option configured as expected
  shell:
    cmd: sysctl --system
  register: sysctl_result
  failed_when: '"net.bridge.bridge-nf-call-iptables = 1" in sysctl_result.stdout'

- name: set storage driver to overlay
  lineinfile:
    dest: /etc/containers/storage.conf
    regexp: "^driver = \"\""
    line: "driver = \"overlay\""
  become: True

- name: run and enable cri-o service
  ansible.builtin.systemd:
    enabled: True
    state: started
    name: crio

- name: check netfilter option configured as expected
  command: crio-status config
  become: True

# download crictl
- name: create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    recurse: yes
  become: True

- name: download crictl
  shell:
    cmd: |
      CRICTL_VERSION="v1.16.0"
      curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /usr/local/bin -xz
  become: True
