# setup kubelet
- name: create /home/ansible/k8s-aur
  file:
    path: /home/ansible/k8s-aur
    state: directory
    recurse: yes

- name: git clone kubelet
  git:
    repo: "https://aur.archlinux.org/kubelet-bin.git"
    dest: /home/ansible/k8s-aur/kubelet
    version: afc29d7b # v1.20.5

- name: makepkg kubelet
  shell:
    cmd: makepkg --noconfirm -si
    chdir: /home/ansible/k8s-aur/kubelet

# this setting is required when you use cri-o
- name: set kubelet cgroup driver to systemd
  lineinfile:
    dest: /var/lib/kubelet/config.yaml
    regexp: "^cgroupDriver: \"systemd\""
    line: "cgroupDriver: \"systemd\""
  become: True

- name: enable kubelet service
  systemd:
    enabled: True
    state: started
    name: kubelet
