- name: git clone kubeadm
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/kubeadm-bin.git"
    dest: /home/ansible/k8s-aur/kubeadm
    version: 2305caa # v1.20.5

- name: makepkg kubeadm
  shell:
    cmd: makepkg --noconfirm -si
    chdir: /home/ansible/k8s-aur/kubeadm

