# setup kubelet
- name: create /home/ansible/k8s-aur
  file:
    path: /home/ansible/k8s-aur
    state: directory
    recurse: yes

- name: git clone kubelet
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/kubelet-bin.git"
    dest: /home/ansible/k8s-aur/kubelet
    version: afc29d7b # v1.20.5

- name: makepkg kubelet
  shell:
    cmd: makepkg --noconfirm -si
    chdir: /home/ansible/k8s-aur/kubelet
