- name: copy bash profile for ansible user
  copy:
    src: .bash_profile
    dest: /home/ansible/
    group: wheel
    owner: ansible

# load bash_profile for following processes
- name: source .bash_profile
  shell: source /home/ansible/.bash_profile